name: 'Release to npmjs.com'

concurrency: ${{ github.workflow }}-${{ github.ref }}

# https://github.com/semantic-release/semantic-release/issues/2481#issuecomment-1409780688
permissions:
  contents: write

on:
  push:
    branches:
      - canary
      # - main

jobs:
  audit-build-test-release:
    name: Audit, build, test, release all packages on ${{ matrix.os }}, Node ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # Use the Active LTS for this workflow
        # https://nodejs.org/en/about/previous-releases
        node: [lts/Jod]
    steps:
      - name: ðŸ›Žï¸ Checkout repo
        uses: actions/checkout@v4

      - name: âš™ï¸ Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: â¬‡ï¸ Install dependencies
        run: npm install
        # run: npm ci

      - name: ðŸ›¡ï¸ Audit dependencies (audit-level high)
        # https://docs.npmjs.com/cli/v8/commands/npm-audit#audit-level
        run: npm audit --audit-level high

      - name: ðŸ›¡ï¸ Audit dependencies (audit-level moderate)
        continue-on-error: true
        run: npm audit --audit-level moderate

      - run: npm run clean
      - run: npm run build:ts
      - run: npm run build:readme
      - run: npm run copy:webc

      - run: npm run publint      
      - run: npm run size

      - name: ðŸ” Test all packages
        env:
          JWKS: ${{ secrets.JWKS }}
        run: npx turbo test:ci

      # - run: npx changeset status

      # - name: Create canary versions (pre-release)
      #   # https://github.com/changesets/changesets/blob/main/docs/prereleases.md
      #   if: github.ref == 'refs/heads/canary'
      #   run: >
      #     npx changeset pre enter canary &&
      #     npx changeset version

      - name: ðŸš€ Create Release Pull Request or Publish to npm.js
        # https://github.com/changesets/action
        # https://github.com/changesets/action/issues/69
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_NPM_TOKEN }}
